### ISSUE TITLE
Inclusion in the Kodi official repository?

### ISSUE THREAD

**Issue by aphirst** [catchup4kodi/catchup4kodi#2]
It occurs to me that none of your addons are present in Kodi's official upstream add-on repository. I'm well aware that the Kodi project (rightly) is concerned about legal issues, and it's entirely possible that some of your add-ons would violate those terms (perhaps including NotFilmOn, which, if I understand correctly, views liveTV streams). Regardless, I'm particularly interested in your ITV add-on.

Now, there is an addon for another UK service which *is* in the official Kodi repo, namely [BBC iPlayer](https://kodi.tv/addon/music-add-ons-plugins-video-add-ons/iplayer-www), and there's an official-repo app for [the German ARD Mediathek](https://kodi.tv/addon/plugins-video-add-ons/ard-mediathek), which suggests that "being a catch-up app" is not itself the problem.

(As an aside for the UK, AFAIK the reason there are no Kodi apps for Channels 4 and 5 is that they do some kind of content protection, encryption, or similar - which by negation suggests that this is *not* done for BBC, ITV (or ARD).)

I tried to find out whether this conversation had ever (publicly) occurred, and even (very carefully) asked in #kodi on Freenode IRC, but it seems that your add-ons and repository are unknown to them (and thus, although not explicitly stated on their list, presumed banned or at least strongly suspect).

So - have you ever been in touch with the Kodi developers/maintainers, or otherwise requested inclusion of (some of) your Add-Ons to the upstream repository? Or; is there something about how your add-ons (again, excluding e.g. NotFilmOn) which you know would disqualify them, hence why you never asked?

I've been unsuccessful in figuring out how to directly contact you, so this seems like my only option. I look forward to your feedback.

**Comment by ghost** [comment]
only reason is because cannot be arsed with changing all code to comply with kodi official in general

**Comment by aphirst** [comment]
On inspection, I suspect that [functionality like this](https://github.com/catchup4kodi/catchup4kodi/blob/master/plugin.video.itv/grabnewip.py) would disqualify the ITV plugin from the official repo. On the other hand, a version which only works if you legitimately do have a UK IP, gracefully failing otherwise, would probably be accepted.
