### ISSUE TITLE
Using Proxy Streams Drop After 60 Seconds (plugin.video.itv)

### ISSUE THREAD

**Issue by Jockula** [catchup4kodi/catchup4kodi#7]
Hey,

Had an issue for a week or two where the steams connect, then drop after just over a minute.  Using a proxy though justproxy.

Log showing as follow, can provide more tests/info as needed.

Thanks for all your work.

> 20:05:18.252 T:1926261248  NOTICE: VideoPlayer: Opening: rtmpe://cp72511.edgefcs.net/ondemand?auth=eaEcmd.c0cvcma2aWbAcQb8c_cXbdcEd9dHdEdJaKbdakdNdfaKdrcpdnalb4akdMdF-bAZiXE-eS-6Ao3EColxrAp&aifp=v002&slist=production/ swfurl=http://www.itv.com/mercury/Mercury_VideoPlayer.swf playpath=mp4:production/priority/CATCHUP/2/3726/0184/001/2-3726-0184-001_PC011800_16X9.mp4 swfvfy=true|X-Forwarded-For=178.79.138.160
20:05:18.252 T:1926261248 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:05:18.253 T:1287648000  NOTICE: Creating InputStream
20:05:48.329 T:1287648000  NOTICE: Creating Demuxer
20:05:48.701 T:1287648000  NOTICE: Opening stream: 0 source: 256
20:05:48.734 T:1287648000  NOTICE: Creating video thread
20:05:48.734 T:1287648000  NOTICE: Opening stream: 1 source: 256
20:05:48.738 T:1287648000  NOTICE: Creating audio thread
20:05:48.738 T:1287648000  NOTICE: Opening stream: 0 source: 1024
20:05:58.032 T:1287648000   ERROR: OpenStream - Unable to create subtitle parser
20:05:58.051 T:1926247168 WARNING: Unable to query optimizer_switch: 'MyVideos107' (1)
20:05:58.130 T:1287648000 WARNING: Previous line repeats 1 times.
20:05:58.131 T:1287648000  NOTICE: OMXClock using audio as reference
20:05:59.855 T:1405088512 WARNING: Unable to query optimizer_switch: 'MyVideos107' (1

**Comment by catchup4kodi** [comment]
fixed please update

**Comment by Jockula** [comment]
Perfect, thanks.

**Comment by chris070475** [comment]
Can u fix bbc iplayer aswell please as since justproxy was removed its no longer working for me
